// Code generated by goyacc -l -o sql.go sql.y. DO NOT EDIT.
package sql

import __yyfmt__ "fmt"

func setParseTree(yylex interface{}, stmt Statement) {
	yylex.(*Lexer).ParseTree = stmt
}

func setDDL(yylex interface{}, ddl *DDL) {
	yylex.(*Lexer).partialDDL = ddl
}

type yySymType struct {
	yys              int
	empty            struct{}
	statement        Statement
	selStmt          SelectStatement
	selectExprs      SelectExprs
	selectExpr       SelectExpr
	expr             Expr
	colName          *ColName
	colIdent         ColIdent
	tableIdent       TableIdent
	bytes            []byte
	tableExprs       TableExprs
	tableExpr        TableExpr
	tableName        TableName
	tableNames       TableNames
	TableSpec        *TableSpec
	aliasedTableName *AliasedTableExpr
	columnDefinition *ColumnDefinition
	columnType       ColumnType
	colKeyOpt        ColumnKeyOption
	ddl              *DDL
	optVal           *SQLVal
	boolVal          BoolVal

	string string
	str    string
}

const SELECT = 57346
const FROM = 57347
const COMMA = 57348
const AS = 57349
const LPAREN = 57350
const RPAREN = 57351
const COUNT = 57352
const WHERE = 57353
const AND = 57354
const OR = 57355
const NOT = 57356
const EQUAL = 57357
const INTEGER = 57358
const TEXT = 57359
const BLOB = 57360
const CREATE = 57361
const PRIMARY = 57362
const KEY = 57363
const AUTOINCREMENT = 57364
const TABLE = 57365
const STAR = 57366
const IDENTIFIER = 57367
const STRING = 57368

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"'.'",
	"SELECT",
	"FROM",
	"COMMA",
	"AS",
	"LPAREN",
	"RPAREN",
	"COUNT",
	"WHERE",
	"AND",
	"OR",
	"NOT",
	"EQUAL",
	"INTEGER",
	"TEXT",
	"BLOB",
	"CREATE",
	"PRIMARY",
	"KEY",
	"AUTOINCREMENT",
	"TABLE",
	"STAR",
	"IDENTIFIER",
	"STRING",
	"'!'",
	"'<'",
	"'>'",
	"';'",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 27,
	4, 24,
	-2, 23,
}

const yyPrivate = 57344

const yyLast = 107

var yyAct = [...]int8{
	25, 79, 62, 16, 30, 24, 17, 38, 14, 10,
	65, 43, 26, 71, 41, 26, 19, 26, 80, 19,
	51, 28, 40, 46, 44, 45, 15, 27, 23, 50,
	27, 23, 27, 23, 31, 50, 51, 41, 39, 49,
	66, 67, 60, 36, 37, 40, 89, 68, 90, 69,
	87, 36, 7, 72, 36, 37, 41, 73, 74, 55,
	56, 57, 59, 76, 82, 53, 81, 8, 52, 48,
	12, 34, 33, 77, 47, 9, 1, 86, 50, 88,
	84, 81, 85, 83, 75, 54, 29, 11, 6, 64,
	63, 61, 32, 78, 35, 70, 21, 42, 58, 18,
	22, 20, 13, 5, 3, 4, 2,
}

var yyPact = [...]int16{
	47, -1000, -22, -1000, -1000, -1000, 61, 1, -3, -1000,
	-1000, -1000, 8, 65, -1000, -1000, 30, -5, -1000, 4,
	-1000, -1000, -1000, -1000, -1000, 70, 60, -1000, -6, 58,
	-1000, 42, 50, 1, -6, -1000, 4, 4, -1000, 11,
	-1000, -1000, 6, -1000, -1000, -1000, -1000, -12, 1, -1000,
	-1000, -1000, -1000, 8, -1000, -1000, -1000, -1000, -1000, 4,
	-1000, 66, -1000, -1000, -1000, 10, -1000, 38, -1000, -1000,
	-1000, -1000, -1000, 54, -1000, -1000, 41, -6, -1000, -1000,
	-6, -1000, -1000, 29, -1000, -1000, 23, 26, -1000, -1000,
	-1000,
}

var yyPgo = [...]int8{
	0, 106, 105, 104, 103, 102, 8, 3, 101, 6,
	100, 99, 98, 97, 96, 5, 95, 94, 7, 0,
	1, 93, 92, 91, 2, 90, 10, 89, 4, 88,
	87, 86, 85, 84, 83, 79, 77, 76, 75,
}

var yyR1 = [...]int8{
	0, 37, 38, 38, 1, 1, 3, 4, 5, 5,
	6, 6, 7, 9, 9, 9, 11, 8, 13, 13,
	13, 14, 14, 15, 19, 16, 16, 17, 17, 17,
	18, 10, 22, 22, 12, 12, 7, 7, 7, 7,
	23, 23, 24, 25, 27, 26, 21, 21, 21, 20,
	2, 29, 30, 31, 31, 28, 32, 32, 32, 33,
	34, 36, 36, 35, 35,
}

var yyR2 = [...]int8{
	0, 2, 0, 1, 1, 1, 1, 4, 1, 3,
	1, 2, 1, 1, 1, 1, 3, 1, 1, 1,
	1, 1, 3, 1, 1, 1, 1, 0, 1, 2,
	1, 4, 0, 2, 0, 2, 1, 3, 3, 2,
	1, 3, 1, 1, 2, 1, 0, 1, 2, 1,
	2, 3, 3, 1, 3, 6, 1, 1, 1, 0,
	0, 0, 2, 0, 1,
}

var yyChk = [...]int16{
	-1000, -37, -1, -3, -2, -4, -29, 5, 20, -38,
	31, -30, 9, -5, -6, 25, -7, -9, -11, 15,
	-8, -14, -10, 27, -15, -19, 11, 26, 24, -31,
	-28, 26, -22, 7, 6, -17, 13, 14, -18, 8,
	-15, 26, -13, 16, 29, 30, -7, 4, 9, -26,
	-19, 26, 10, 7, -32, 17, 18, 19, -12, 12,
	-6, -23, -24, -25, -27, -26, -7, -7, -18, -9,
	-16, 25, -15, -6, -28, -33, -7, 7, -21, -20,
	8, -19, 10, -34, -24, -20, -36, 21, -35, 23,
	22,
}

var yyDef = [...]int8{
	0, -2, 2, 4, 5, 6, 0, 0, 0, 1,
	3, 50, 0, 32, 8, 10, 27, 12, 36, 0,
	13, 14, 15, 17, 21, 0, 0, -2, 0, 0,
	53, 0, 34, 0, 0, 11, 0, 0, 28, 0,
	30, 23, 0, 18, 19, 20, 39, 0, 0, 51,
	45, 24, 52, 0, 59, 56, 57, 58, 7, 0,
	9, 33, 40, 42, 43, 46, 37, 38, 29, 16,
	22, 25, 26, 0, 54, 60, 35, 0, 44, 47,
	0, 49, 31, 61, 41, 48, 63, 0, 55, 64,
	62,
}

var yyTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 28, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 4, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 31,
	29, 3, 30,
}

var yyTok2 = [...]int8{
	2, 3, 5, 6, 7, 8, 9, 10, 11, 12,
	13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
	23, 24, 25, 26, 27,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			setParseTree(yylex, yyDollar[1].statement)
		}
	case 2:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
		}
	case 3:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
		}
	case 4:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.statement = yyDollar[1].selStmt
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			sel := yyDollar[1].selStmt.(*Select)
			yyVAL.selStmt = sel
		}
	case 7:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.selStmt = &Select{SelectExprs: yyDollar[2].selectExprs, From: yyDollar[3].tableExprs, Where: NewWhere(WhereStr, yyDollar[4].expr)}
		}
	case 8:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.selectExprs = SelectExprs{yyDollar[1].selectExpr}
		}
	case 9:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.selectExprs = append(yyVAL.selectExprs, yyDollar[3].selectExpr)
		}
	case 10:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.selectExpr = &StarExpr{}
		}
	case 11:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.selectExpr = &AliasedExpr{Expr: yyDollar[1].expr, As: yyDollar[2].colIdent}
		}
	case 12:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 13:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 14:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.expr = yyDollar[1].colName
		}
	case 15:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 16:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.expr = &ComparisonExpr{Left: yyDollar[1].expr, Operator: yyDollar[2].str, Right: yyDollar[3].expr}
		}
	case 17:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.expr = NewStrVal([]byte(yyDollar[1].str))
		}
	case 18:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.str = EqualStr
		}
	case 19:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.str = LessThanStr
		}
	case 20:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.str = GreaterThanStr
		}
	case 21:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.colName = &ColName{Name: yyDollar[1].colIdent}
		}
	case 22:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.colName = &ColName{Qualifier: TableName{Name: yyDollar[1].tableIdent}, Name: yyDollar[3].colIdent}
		}
	case 23:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.colIdent = NewColIdent(string(yyDollar[1].str))
		}
	case 24:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.tableIdent = NewTableIdent(string(yyDollar[1].str))
		}
	case 25:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.colIdent = NewColIdent(string('*'))
		}
	case 26:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.colIdent = yyDollar[1].colIdent
		}
	case 27:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.colIdent = ColIdent{}
		}
	case 28:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.colIdent = yyDollar[1].colIdent
		}
	case 29:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.colIdent = yyDollar[2].colIdent
		}
	case 30:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.colIdent = yyDollar[1].colIdent
		}
	case 31:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.expr = &FuncExpr{Name: NewColIdent("count"), Exprs: NewSelectExprs(yyDollar[3].selectExpr)}
		}
	case 32:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.tableExprs = TableExprs{&AliasedTableExpr{Expr: TableName{Name: NewTableIdent("dual")}}}
		}
	case 33:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.tableExprs = yyDollar[2].tableExprs
		}
	case 34:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.expr = nil
		}
	case 35:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.expr = yyDollar[2].expr
		}
	case 36:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 37:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.expr = &AndExpr{Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 38:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.expr = &OrExpr{Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 39:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.expr = &NotExpr{Expr: yyDollar[2].expr}
		}
	case 40:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.tableExprs = TableExprs{yyDollar[1].tableExpr}
		}
	case 41:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.tableExprs = append(yyVAL.tableExprs, yyDollar[3].tableExpr)
		}
	case 42:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.tableExpr = yyDollar[1].tableExpr
		}
	case 43:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.tableExpr = yyDollar[1].aliasedTableName
		}
	case 44:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.aliasedTableName = &AliasedTableExpr{Expr: yyDollar[1].tableName, As: yyDollar[2].tableIdent}
		}
	case 45:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.tableName = TableName{Name: yyDollar[1].tableIdent}
		}
	case 46:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.tableIdent = NewTableIdent("")
		}
	case 47:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.tableIdent = yyDollar[1].tableIdent
		}
	case 48:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.tableIdent = yyDollar[2].tableIdent
		}
	case 49:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.tableIdent = yyDollar[1].tableIdent
		}
	case 50:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyDollar[1].ddl.TableSpec = yyDollar[2].TableSpec
			yyVAL.statement = yyDollar[1].ddl
		}
	case 51:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.ddl = &DDL{Action: CreateStr, NewName: yyDollar[3].tableName}
			setDDL(yylex, yyVAL.ddl)
		}
	case 52:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.TableSpec = yyDollar[2].TableSpec
		}
	case 53:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.TableSpec = &TableSpec{}
			yyVAL.TableSpec.AddColumn(yyDollar[1].columnDefinition)
		}
	case 54:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.TableSpec.AddColumn(yyDollar[3].columnDefinition)
		}
	case 55:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yyDollar[2].columnType.Default = yyDollar[3].optVal
			yyDollar[2].columnType.OnUpdate = yyDollar[4].optVal
			yyDollar[2].columnType.KeyOpt = yyDollar[5].colKeyOpt
			yyDollar[2].columnType.Autoincrement = yyDollar[6].boolVal
			yyVAL.columnDefinition = &ColumnDefinition{Name: NewColIdent(string(yyDollar[1].str)), Type: yyDollar[2].columnType}
		}
	case 56:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.columnType = NewIntegerColumn()
		}
	case 57:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.columnType = NewTextColumn()
		}
	case 58:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.columnType = NewBlobColumn()
		}
	case 59:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.optVal = nil
		}
	case 60:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.optVal = nil
		}
	case 61:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.colKeyOpt = ColKeyNone
		}
	case 62:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.colKeyOpt = ColKeyPrimary
		}
	case 63:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.boolVal = BoolVal(false)
		}
	case 64:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.boolVal = BoolVal(true)
		}
	}
	goto yystack /* stack new state and value */
}
